server:
  port: 8090
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_jxc?useSSL=false&useUnicode=true&amp;characterEncoding=utf-8
    username: hao
    password: 1122
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true